"""Opening cutscene of a new game (island `autorun`, plays once: flag st_intro). Used by make_island.py and by the one-off patch of island.json."""
S = lambda who, text: dict(type="say", who=who, text=text)
INTRO = [
    # saves that already have story progress are marked as having seen it by hub3d.js, so this only ever plays on a fresh game
    dict(unless="st_intro", cine=True, actions=[
        dict(type="cine", on=True), dict(type="music", url="/assets/Music/mp3/17. Unknown Island.mp3"),
        dict(type="tp", x=-0.2, z=30.2, fade=False), dict(type="face", who="player", dir="north"),
        dict(type="cam", x=-4, z=-4, yaw=28, pitch=27, dist=58, t=0),
        dict(type="wait", t=0.8),
        dict(type="title", text="SkyBourne Saga", sub="Those born of the sky will shape reality itself.", t=4.6),
        dict(type="fade", to="clear", t=2.4, wait=False),
        dict(type="cam", x=3, z=14, yaw=-8, pitch=24, dist=44, t=22, wait=False),
        S("", "On a small island in a faraway sea, a legend is about to be born."),
        S("", "A young swordsman, with no past and no future, has come to seek his fortune."),
        S("", "But every legend starts somewhere small. Today, that somewhere is Paradise Island."),
        dict(type="cam", x=0, z=25.5, yaw=-14, pitch=21, dist=19, t=2.6),
        dict(type="walk", who="player", x=0, z=25.4, speed=2.6),
        dict(type="face", who="player", dir="south"),
        dict(type="wait", t=0.5),
        S("Ferryman Osk", "End of the line, friend. This is my last stop for the day."),
        S("Kenji", "Suits me. I need to try an earn some money anyway."),
        S("Ferryman Osk", "Ha! What does a swordsman want on Paradise Island, anyway? Nothing here but fishermen and Trees."),
        S("Kenji", "I'm not really sure, but something tells me this is where I need to be... for now."),
        S("Ferryman Osk", "Ahh, a man who lets the sea be his guide, I can relate to that."),
        S("Ferryman Osk", "If it's work you're after, the mayor has been asking about  lately swordsmen. Big blue-roofed house, up the hill past the plaza. You can't miss it."),
        S("Kenji", "I'll check it out. Thanks for the tip, Osk."),
        dict(type="face", who="player", dir="north"),
        dict(type="follow", t=0.6),
        dict(type="walk", who="player", x=0, z=14.5, speed=4.4),
        dict(type="cam", x=19, z=-17, yaw=-12, pitch=27, dist=34, t=3.2),
        S("", "Up the hill, past the fountain, the mayor's blue-roofed house watches over the harbour. Whatever he wants, it won't be a quiet job."),
        S("Kenji", "Alright, Let's see what this Orrin guy has to say. Hopefully its a job, and maybe a meal would be nice."),
        dict(type="follow", t=1.8),
        dict(type="flag", key="st_intro"),
        S("", "Move with WASD or the arrow keys (Shift to run), or click the ground. Press E to talk. Find Mayor Orrin."),
    ]),
]
